#!/bin/bash

echo "🏀 NBA Fantasy AI Production Setup"
echo "==================================="

cd ~/nba-backend

echo ""
echo "Step 1: Update .env file for production"
echo "----------------------------------------"
echo "Edit your .env file and change:"
echo ""
echo "From:"
echo "  NODE_ENV=development"
echo "  ENV_PROD=false"
echo "  DOMAIN=http://localhost:3000"
echo "  ALLOWED_ORIGINS=http://localhost:8081,http://10.0.0.183:8081"
echo ""
echo "To:"
echo "  NODE_ENV=production"
echo "  ENV_PROD=true"
echo "  DOMAIN=https://api.yourdomain.com"
echo "  ALLOWED_ORIGINS=https://app.yourdomain.com"
echo ""
echo "Also update:"
echo "  • MONGODB_URI to production database"
echo "  • JWT_SECRET to a secure random string"
echo "  • LOG_LEVEL to 'warn' or 'error'"
echo "  • Stripe keys to live keys"
echo ""
echo "Step 2: Install PM2 for process management"
echo "-------------------------------------------"
echo "npm install -g pm2"
echo ""
echo "Step 3: Start server with PM2"
echo "------------------------------"
echo "pm2 start server.js --name nba-fantasy-api"
echo ""
echo "Step 4: Configure PM2 to start on boot"
echo "---------------------------------------"
echo "pm2 startup"
echo "pm2 save"
echo ""
echo "Step 5: Configure Nginx (if using)"
echo "-----------------------------------"
echo "See nginx-config.example in the repo"
echo ""
echo "Production checklist:"
echo "✅ Environment variables set"
echo "✅ CORS configured for production domains"
echo "✅ Database connection to production DB"
echo "✅ Secure JWT secret"
echo "✅ Production logging level"
echo "✅ Process manager (PM2) installed"
echo "✅ SSL certificates configured"
